apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.name" . }}-rail
  namespace: osrm
  labels:
    {{- include "common.labels" . | indent 4 }}
    app: osrm-rail
spec:
  progressDeadlineSeconds: 5400
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "app.name" . }}-rail
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "common.labels" . | indent 8 }}
        app: osrm-rail
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - osrm-bus
                        - osrm-rail
                        - osrm-water
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - name: {{ .Chart.Name }}-rail
          image: {{ .Values.image.identifier }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          command:
            - /deployments/docker-entrypoint.sh
            - osrm
            - rail
            - https://storage.googleapis.com/{{ .Values.cronJob.gcpBucketName }}
          env:
            - name: TZ
              value: Europe/Oslo
          resources:
            limits:
              cpu: {{ .Values.resources.cpuLimit }}
              memory: {{ .Values.resources.memLimit }}
            requests:
              cpu: {{ .Values.resources.cpuRequest }}
              memory: {{ .Values.resources.memRequest }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: {{ .Values.service.http.internalPort }}
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /table/v1/driving/10.8116303,59.9096267;10.7502687,59.911096?sources=0
              port: {{ .Values.service.http.internalPort }}
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      terminationGracePeriodSeconds: 31

