apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cronjob-redeploy-{{ template "app.name" . }}
  namespace: osrm
  labels:
    {{- include "common.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cronjob-redeploy-{{ template "app.name" . }}
subjects:
  - kind: ServiceAccount
    name: application
    namespace: osrm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cronjob-redeploy-{{ template "app.name" . }}
  namespace: osrm
  labels:
    {{- include "common.labels" . | indent 4 }}
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - watch
      - list
      - update
      - patch
