{{- range $secretName, $secretValues := .Values.secrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secretName }}
  labels: {{ $.Values.labels }}
  annotations:
    timestamp: {{ now | date "2006-01-02T15:04:05" }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ $.Release.Namespace }}
  target:
    name: {{ $secretName }}
    creationPolicy: Owner
  data:
  {{- range $secretValues }}
  - secretKey: {{ . }}
    remoteRef:
      key: {{ . }}
  {{- end }}
---
{{- end }}
