apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "common.labels" . | indent 4 }}
    app: osrm-water
  name: {{ template "app.name" . }}-water
  namespace: osrm
spec:
  ports:
    - name: http
      port: {{ .Values.service.http.externalPort }}
      protocol: TCP
      targetPort: {{ .Values.service.http.internalPort }}
  selector:
    app: {{ template "app.name" . }}-water
  sessionAffinity: None
  type: ClusterIP
